### ISSUE TITLE
Regression in reference to 1.1.1

### ISSUE THREAD

**Issue by mensfeld** [dry-rb/dry-validation#566]
Code that was working in `1.1.1` related to not executing custom rules when schema not matched for a given attribute does not work in `1.2.0`.

Given a definition like that (see [here](https://github.com/karafka/waterdrop/blob/6926bdb7d1ffb71d6cebe70218359168d95314f2/lib/water_drop/contracts/config.rb#L50))

```ruby
required(:seed_brokers).value(:array, :filled?).each(:str?)
```

and a custom rule as followed [here](https://github.com/karafka/waterdrop/blob/6926bdb7d1ffb71d6cebe70218359168d95314f2/lib/water_drop/contracts/config.rb#L96):

```ruby
kafka_scope_rule(:seed_brokers) do |kafka|
  unless kafka[:seed_brokers].all?(&method(:broker_schema?))
     key(%i[kafka seed_brokers]).failure(:broker_schema)
  end
end
```

The custom rule is executed even when the requirements of the schema are not met.

Reproduction:

```ruby
mkdir broken
cd broken
git clone https://github.com/karafka/waterdrop/ ./
# Old dry-validation having commit (1.1.1)
git checkout d35bf09d140ebbfbc29911638c5ddfbe578cfd90
bundle
# All will be green
bundle exec rspec spec
# Force upgrade
rm Gemfile.lock
bundle
# That one will fail
bundle exec rspec spec
```

second will fail with:

```
1) WaterDrop::Contracts::Config when we run kafka.seed_brokers validations when seed_brokers are not an array 
     Failure/Error: unless kafka[:seed_brokers].all?(&method(:broker_schema?))
     
     NoMethodError:
       undefined method `all?' for 0.24300762037486034:Float
     # ./lib/water_drop/contracts/config.rb:97:in `block in <class:Config>'
     # ./lib/water_drop/contracts/config.rb:26:in `instance_exec'
     # ./lib/water_drop/contracts/config.rb:26:in `block in kafka_scope_rule'
     # ./spec/lib/water_drop/contracts/config_spec.rb:134:in `block (4 levels) in <top (required)>'

  2) WaterDrop::Contracts::Config when we run kafka.seed_brokers validations when seed_brokers are missing 
     Failure/Error: unless kafka[:seed_brokers].all?(&method(:broker_schema?))
     
     NoMethodError:
       undefined method `all?' for nil:NilClass
     # ./lib/water_drop/contracts/config.rb:97:in `block in <class:Config>'
     # ./lib/water_drop/contracts/config.rb:26:in `instance_exec'
     # ./lib/water_drop/contracts/config.rb:26:in `block in kafka_scope_rule'
     # ./spec/lib/water_drop/contracts/config_spec.rb:122:in `block (4 levels) in <top (required)>'
```

**Comment by solnic** [comment]
This is not valid. Previous behavior was broken and waterdrop relied on that by an accident (which I fixed in the referred PR)
