### ISSUE TITLE
Error when applying a rule to array using each

### ISSUE THREAD

**Issue by rrjohnson85** [dry-rb/dry-validation#553]
**Describe the bug**

When trying to use `each` against an array nested in a hash, I receive the following error:

`NoMethodError (undefined method `each_with_index' for nil:NilClass)`

In addition to this, it would seem the string dot notation does not work reliably (ex. `'path.to.some.array'`).

It seems this sort of worked with v1.0 (there were issues, but didn't get an exception; see https://github.com/dry-rb/dry-validation/pull/543).  This seems to have appeared in v1.1.

**To Reproduce**
```ruby
class TestContract < Dry::Validation::Contract
  register_macro(:required_status) do
    key.failure('Status is required') if value.dig(:status).blank?
  end

  params do
    required(:top_level_array).value(:array)
    required(:top_level_hash).hash do
      required(:second_level_array).array(:hash)
      # required(:second_level_hash).hash do
      #   required(:third_level_array).array(:hash) do
      #     required(:status).maybe(:string, included_in?: %w[one two three])
      #   end
      # end
    end
  end

  # Does not work
  # rule('top_level_hash.second_level_hash.third_level_array').each(:required_status)

  # Does not work
  # rule('top_level_hash.second_level_hash.third_level_array').each do
  #   key.failure('Status is required') if value.dig(:status).blank?
  # end

  # Does not work
  # rule(top_level_hash: { second_level_hash: [:third_level_array] }).each do
  #   key.failure('Status is required') if value.dig(:status).blank?
  # end

  # Does not work
  # rule(top_level_hash: [second_level_hash: [:third_level_array]]).each do
  #   key.failure('Status is required') if value.dig(:status).blank?
  # end

  # Works
  rule(:top_level_array).each(:required_status)

  # Does not work
  # rule('top_level_array').each(:required_status)

  # Does not work
  # rule('top_level_hash.second_level_array').each(:required_status)
end
```

**Expected behavior**
I would expect that a `rule` with a `each` works and that the paths used elsewhere work similarly.

**Your environment**
- Affects my production application: Yes
- Ruby version: 2.5.1
- OS: MacOS Mojave (10.14.5 (18F132))
- dry-validation: v1.1

**Comment by solnic** [comment]
could you try master?

**Comment by rrjohnson85** [comment]
@solnic I'm going to keep messing with this a bit more, but the scenarios I've outlined above that I've tested seem to be working.

**Comment by solnic** [comment]
@rrjohnson85 the only change between 1.1.0 and master was #552 which seems related

**Comment by rrjohnson85** [comment]
@solnic I've tested master a bit further and am still not sure the `rule` paths are working 100% as expected.  See update repro below:
```ruby
class TestContract < Dry::Validation::Contract
  register_macro(:required_status) do
    key.failure('Status is required') if value.dig(:status).blank?
  end

  params do
    required(:top_level_array).value(:array)
    required(:top_level_hash).hash do
      required(:second_level_array).array(:hash)
      required(:second_level_hash).hash do
        required(:third_level_array).array(:hash) do
          required(:status).maybe(:string)
        end
      end
    end
  end

  # Works in master
  # rule('top_level_hash.second_level_hash.third_level_array').each(:required_status)

  # Works in master
  # rule('top_level_hash.second_level_hash.third_level_array').each do
  #   key.failure('Status is required') if value.dig(:status).blank?
  # end

  # Does not work in master - value is nil
  # rule(top_level_hash: { second_level_hash: [:third_level_array] }).each do
  #   key.failure('Status is required') if value.dig(:status).blank?
  # end

  # Does not work in master - value is nil
  # rule(top_level_hash: [second_level_hash: [:third_level_array]]).each do
  #   key.failure('Status is required') if value.dig(:status).blank?
  # end

  # Does not work in master - value is nil
  # rule(top_level_hash: [second_level_hash: [:third_level_array]]).each(:required_status)

  # Does not work in master - value is nil
  # rule(top_level_hash: { second_level_hash: [:third_level_array] }).each(:required_status)

  # Works in master
  rule([:top_level_hash, :second_level_hash, :third_level_array]).each(:required_status)

  # Works in 1.1/master
  rule(:top_level_array).each(:required_status)
end
```

Should `rule(top_level_hash: [second_level_hash: [:third_level_array]])` or `rule(top_level_hash: { second_level_hash: [:third_level_array] })` work?

**Comment by solnic** [comment]
> Should rule(top_level_hash: [second_level_hash: [:third_level_array]]) or rule(top_level_hash: { second_level_hash: [:third_level_array] }) work?

No, this is not supposed to work. We could raise an error in cases like that.

**Comment by rrjohnson85** [comment]
Thanks for everything @solnic.  Having an error for bad paths might be helpful, but may not be necessary.

**Comment by solnic** [comment]
@rrjohnson85 I'll see how this could be improved
