### ISSUE TITLE
Specify custom predicates globally

### ISSUE THREAD

**Issue by ineu** [dry-rb/dry-validation#122]
In 0.6 I used to have a custom predicates module and the following line in my initializer file:
```ruby
Dry::Validation::Schema.config.predicates = DryValidationPredicates
```
Unfortunately this no longer works in 0.7. This syntax throws 'undefined method `options`' exception on defining schema.
So I have to use `configure do` block for every single schema. This is cumbersome, the old approach was much easier.
So my question is: what is the way to define additional predicates globally, without repeating `configure` blocks in every schema?
Thanks.

**Comment by AMHOL** [comment]
@ineu sorry for the late reply, could you show the code for `DryValidationPredicates`, the following doesn't throw any errors for me:

```ruby
require 'bundler/inline'

gemfile(true) do
  gem 'dry-validation', '~> 0.7'
end

module DryValidationPredicates; end
Dry::Validation::Schema.config.predicates = DryValidationPredicates

```

**Comment by AMHOL** [comment]
@ineu this is fixed in master, please use the master branch until the 0.8.0 release

**Comment by ineu** [comment]
Awesome, thank you!
